apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: counter-app:latest
        ports:
        - containerPort: 3000
